development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ClipIt_development
  pool: 5
  username: johncapecelatro
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ClipIt_test
  pool: 5
  username: johncapecelatro
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ClipIt_production
  pool: 5
  username: johncapecelatro
  password:
